### ISSUE TITLE
Would love to help, can you document some things you would like done?

### ISSUE THREAD

**Issue by fabianvf** [elifoster/GHULS#10]
I am particularly interested in helping to get a web app up and running, if you are open to it.

**Comment by elifoster** [comment]
I would love to have a web app for this. I tried to make a desktop app with webkits, but getting it working with Perl was either a gigantic pain in the ass or impossible. I'm not the best with CSS, but when I was trying to do it with CSS I made some branches with some basic styles. 

What languages would the web stuff be written in? I would like to keep the Perl backend. I could very easily change the Perl script to work with whatever is written.

Having a web app for GHULS would be great, because it would expand the possibilities for the software very, very greatly. If you want to get started on that, go ahead and make a fork, and when ready, request a merge.

**Comment by fabianvf** [comment]
I am most comfortable with python for webapps. I'll play around with it a bit and see what it would take.
